name: studyforge
description: A reviewer app with questionnaires.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.5+3
  flutter_native_splash: ^2.2.10+1
  tflite: ^1.1.2
  cloud_firestore: ^4.4.2
  firebase_core: ^2.6.1
  firebase_auth: ^4.2.8
  url_launcher: ^6.0.0

flutter_native_splash:
  color: "#f8f8f8"
  image: assets/images/logo.png
  web: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/LauncherIcon.png"
    background_color: "#f8f8f8"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/LauncherIcon.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:
  uses-material-design: true
  assets:
  - assets/images/Fritz_pic.jpg
  - assets/images/logo.png
  - assets/Images_of_Plant/0.png
  - assets/Images_of_Plant/1.png
  - assets/Images_of_Plant/2.png
  - assets/Images_of_Plant/3.png
  - assets/Images_of_Plant/4.png
  - assets/Images_of_Plant/5.png  
  - assets/Images_of_Plant/6.png  
  - assets/Images_of_Plant/7.png  
  fonts:
    - family: RobotoBold
      fonts:
        - asset: assets\fonts\Roboto-Bold.ttf
    - family: RobotoMedium
      fonts:
        - asset: assets\fonts\Roboto-Medium.ttf   
    - family: RobotoLight
      fonts: 
        - asset: assets\fonts\Roboto-Light.ttf